version: '3.7'

services:
  referentie-api:
    container_name: referentie-api
    image: ghcr.io/brp-api/brp-referentie-api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5010
      - Ecs__Path=/var/log/brp-referentie-api.json
      - Ecs__FileSizeLimitBytes=1048576
      - Ecs__RetainedFileCountLimit=10
    ports:
      - "5010:5010"
    volumes:
      - ../test-data/logs:/var/log
    networks:
      - brp-api-network

networks:
  brp-api-network:
    name: brp-api-network
