name: continuous integration

on:
  push:
    paths:
      - src/**
      - features/**
      - .github/workflows/ci.yml
  workflow_dispatch:

env:
  DOTNET_VERSION: 6.0.x
  DOTNET_SOLUTION: src/brp-shared.sln
  NODE_VERSION: '18'
  COMPOSE_FILE_ARGUMENT: -f .docker/db-ci.yml -f .docker/identityserver.yml -f .docker/referentie-api.yml -f .docker/autorisatie-protocollering-proxy.yml
  UPDATE_VERSION_CSPROJ: src/Brp.AutorisatieEnProtocollering.Proxy/Brp.AutorisatieEnProtocollering.Proxy.csproj
  CONTAINER_IMAGE: ghcr.io/brp-api/brp-autorisatie-protocollering
  BUILD_RUN: ''
  APP_VERSION: ''

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Genereer build run identifier
        id: build-run-id
        uses: ./.github/actions/genereer-build-run-identifier
      - name: Genereer versie met build run identifier
        id: app-version
        uses: ./.github/actions/zet-versie-met-build-run-in-csproj
        with:
          path-csproj-file: ${{ env.UPDATE_VERSION_CSPROJ }}
          build-run: ${{ steps.build-run-id.outputs.build-run }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Valideer .NET solution
        uses: ./.github/actions/valideer-dotnet-solution
        with:
          path-solution-file: ${{ env.DOTNET_SOLUTION }}
      - name: Build container images
        run: docker compose -f src/docker-compose.yml build
      - name: Voeg identityserver toe als host naam
        uses: ./.github/actions/toevoegen-localhost-naam
        with:
          host-name: identityserver
      - name: Set read/write permissions on test-data/IdentityServer folder
        run: |
          sudo chmod ugo+rw ./test-data/IdentityServer
      - name: Set run permissions on script folder
        uses: ./.github/actions/zet-run-bash-scripts-permission
        with:
          path-bash-file-or-folder: ./scripts/*
      - name: Start containers
        run: docker compose ${{ env.COMPOSE_FILE_ARGUMENT }} up -d
      - name: Wait for DB restart
        run: sleep 5s
        shell: bash
      - name: Validate functional specs
        run: |
          ./scripts/specs-verify.sh
      - name: Stop containers
        if: always()
        run: docker compose ${{ env.COMPOSE_FILE_ARGUMENT }} down
      - name: Genereer test rapportage
        if: always()
        run: |
          node ./scripts/generate-cucumber-reports.js ${{ steps.app-version.outputs.version }} ${{ steps.build-run-id.outputs.build-run }} ${{ github.ref_name }}
      - name: Upload test rapportage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Reports
          path: test-reports
      - name: Push test rapportage naar brp-api.github.io repo
        if: always()
        uses: tech-thinker/push-to-repo@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GIT_PAT_TOKEN }}
        with:
          source-directory: test-reports/cucumber-js/reports
          destination-repository-name: brp-api.github.io
          destination-github-username: BRP-API
          target-branch: test-reports/autorisatie-en-protocollering
          commit-message: "test rapporten van build: ${{ steps.build-run-id.outputs.build-run }}"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag & push container images naar registry
        run: |
          docker tag ${{ env.CONTAINER_IMAGE }}:latest ${{ env.CONTAINER_IMAGE }}:${{ steps.app-version.outputs.version }}-latest
          docker tag ${{ env.CONTAINER_IMAGE }}:latest ${{ env.CONTAINER_IMAGE }}:${{ steps.app-version.outputs.version }}-${{ steps.build-run-id.outputs.build-run }}
          docker push ${{ env.CONTAINER_IMAGE }}:${{ steps.app-version.outputs.version }}-latest
          docker push ${{ env.CONTAINER_IMAGE }}:${{ steps.app-version.outputs.version }}-${{ steps.build-run-id.outputs.build-run }}
